name: WinWM


on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: build
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        ./build.bat
    - uses: actions/upload-artifact@v2
      with:
        name: winwm - release build
        path: Build

