name: CI/CD Github actions

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    name: "WinWM"
    runs-on: "windows-2016"

  steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cmd "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
        build.bat
